/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ıd3_alg;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import static java.lang.String.valueOf;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Ersn
 */
public class anasayfa extends javax.swing.JFrame {

    /**
     * Creates new form anasayfa
     */
    public anasayfa() {
        //this.setUndecorated(true);
        //this.setAlwaysOnTop(true);
        this.setResizable(false);
        //this.setVisible(true);
        initComponents();
        this.setSize(700, 410);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        
        jPanel_veriEkle.setVisible(false);
        jPanel_veriler.setVisible(false);
        jPanel_sorgulamaYap.setVisible(false);
    }
   /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        AnaPanel = new javax.swing.JPanel();
        labelListele = new javax.swing.JLabel();
        jLabel_sorgulamaYap = new javax.swing.JLabel();
        jPanel_sorgulamaYap = new javax.swing.JPanel();
        jPanel_sonuc = new javax.swing.JPanel();
        jLabel_sonuc = new javax.swing.JLabel();
        jPanel_secimYap = new javax.swing.JPanel();
        jLabel_secim = new javax.swing.JLabel();
        jComboBox_secim = new javax.swing.JComboBox<>();
        jLabel_sorgula = new javax.swing.JLabel();
        jPanel_veriler = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        veriler = new javax.swing.JTable();
        jPanel_veriEkle = new javax.swing.JPanel();
        label_kaydet = new javax.swing.JLabel();
        jPanel_ates = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jPanel_oksuruk = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jComboBox7 = new javax.swing.JComboBox<>();
        jPanel_agri = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jComboBox10 = new javax.swing.JComboBox<>();
        jPanel_halsizlik = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jComboBox8 = new javax.swing.JComboBox<>();
        jPanel_hasta = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jComboBox9 = new javax.swing.JComboBox<>();
        label_veriKaydet = new javax.swing.JLabel();
        jPanel_benKimim = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labelBackgraund = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImages(null);
        setResizable(false);
        setSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(null);

        AnaPanel.setLayout(null);

        labelListele.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelListele.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Contact.png"))); // NOI18N
        labelListele.setText("Tüm Veriler");
        labelListele.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelListele.setDoubleBuffered(true);
        labelListele.setName(""); // NOI18N
        labelListele.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                click(evt);
            }
        });
        AnaPanel.add(labelListele);
        labelListele.setBounds(40, 40, 140, 50);

        jLabel_sorgulamaYap.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_sorgulamaYap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Favorite.png"))); // NOI18N
        jLabel_sorgulamaYap.setText("Sorgulama Yap");
        jLabel_sorgulamaYap.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_sorgulamaYap.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jLabel_sorgulamaYap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_sorgulamaYapMouseClicked(evt);
            }
        });
        AnaPanel.add(jLabel_sorgulamaYap);
        jLabel_sorgulamaYap.setBounds(460, 40, 140, 50);

        jPanel_sorgulamaYap.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_sorgulamaYap.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 204, 255), 15, true));
        jPanel_sorgulamaYap.setForeground(new java.awt.Color(204, 204, 204));
        jPanel_sorgulamaYap.setName(""); // NOI18N
        jPanel_sorgulamaYap.setLayout(null);

        jPanel_sonuc.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 204, 255), 7, true));
        jPanel_sonuc.setLayout(null);

        jLabel_sonuc.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel_sonuc.setText("Yapılan tetkikler sonucunda malesef HASTA olduğunuz tesbit edilmiştir.");
        jPanel_sonuc.add(jLabel_sonuc);
        jLabel_sonuc.setBounds(10, 30, 410, 14);

        jPanel_sorgulamaYap.add(jPanel_sonuc);
        jPanel_sonuc.setBounds(110, 30, 430, 100);

        jPanel_secimYap.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 204, 255), 7, true));
        jPanel_secimYap.setLayout(null);

        jLabel_secim.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_secim.setText("Ateş dereceniz kaç ?");
        jPanel_secimYap.add(jLabel_secim);
        jLabel_secim.setBounds(10, 30, 280, 15);

        jComboBox_secim.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jComboBox_secim.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "start" }));
        jComboBox_secim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_secimActionPerformed(evt);
            }
        });
        jPanel_secimYap.add(jComboBox_secim);
        jComboBox_secim.setBounds(10, 50, 250, 19);

        jLabel_sorgula.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_sorgula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Add Appointment.png"))); // NOI18N
        jLabel_sorgula.setText("İleri");
        jLabel_sorgula.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_sorgula.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jLabel_sorgula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_sorgulaMouseClicked(evt);
            }
        });
        jPanel_secimYap.add(jLabel_sorgula);
        jLabel_sorgula.setBounds(280, 30, 90, 50);

        jPanel_sorgulamaYap.add(jPanel_secimYap);
        jPanel_secimYap.setBounds(130, 30, 380, 100);

        AnaPanel.add(jPanel_sorgulamaYap);
        jPanel_sorgulamaYap.setBounds(30, 130, 630, 170);

        jPanel_veriler.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_veriler.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 204, 255), 15, true));
        jPanel_veriler.setForeground(new java.awt.Color(204, 204, 204));
        jPanel_veriler.setLayout(null);

        veriler.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(veriler);

        jPanel_veriler.add(jScrollPane2);
        jScrollPane2.setBounds(20, 20, 590, 130);

        AnaPanel.add(jPanel_veriler);
        jPanel_veriler.setBounds(30, 130, 630, 170);

        jPanel_veriEkle.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_veriEkle.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 204, 255), 15, true));
        jPanel_veriEkle.setLayout(null);

        label_kaydet.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_kaydet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Add Appointment.png"))); // NOI18N
        label_kaydet.setText("İleri");
        label_kaydet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_kaydet.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        label_kaydet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_kaydetMouseClicked(evt);
            }
        });
        jPanel_veriEkle.add(label_kaydet);
        label_kaydet.setBounds(520, 100, 90, 50);

        jPanel_ates.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 204, 255), 7, true));
        jPanel_ates.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Ateş dereceniz kaç ?");
        jPanel_ates.add(jLabel2);
        jLabel2.setBounds(10, 10, 130, 15);

        jComboBox2.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "33 - 35    Dusuk", "35 - 37    Normal", "37 - 40    Yuksek" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel_ates.add(jComboBox2);
        jComboBox2.setBounds(10, 30, 180, 19);

        jPanel_veriEkle.add(jPanel_ates);
        jPanel_ates.setBounds(220, 30, 200, 100);

        jPanel_oksuruk.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 204, 255), 7, true));
        jPanel_oksuruk.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Öksürüyor musunuz ?");
        jPanel_oksuruk.add(jLabel9);
        jLabel9.setBounds(10, 10, 140, 15);

        jComboBox7.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Evet", "Hayir" }));
        jPanel_oksuruk.add(jComboBox7);
        jComboBox7.setBounds(10, 30, 180, 20);

        jPanel_veriEkle.add(jPanel_oksuruk);
        jPanel_oksuruk.setBounds(220, 30, 200, 100);

        jPanel_agri.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 204, 255), 7, true));
        jPanel_agri.setLayout(null);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Ağrı Dereceniz Nedir ?");
        jPanel_agri.add(jLabel12);
        jLabel12.setBounds(10, 10, 170, 15);

        jComboBox10.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Eh iste", "Turp gibiyim", "Agri dagin eteginde...." }));
        jComboBox10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox10ActionPerformed(evt);
            }
        });
        jPanel_agri.add(jComboBox10);
        jComboBox10.setBounds(10, 30, 180, 19);

        jPanel_veriEkle.add(jPanel_agri);
        jPanel_agri.setBounds(220, 30, 200, 100);

        jPanel_halsizlik.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 204, 255), 7, true));
        jPanel_halsizlik.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Halsizlik yaşıyor musunuz ?");
        jPanel_halsizlik.add(jLabel10);
        jLabel10.setBounds(10, 10, 170, 15);

        jComboBox8.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "iyiyim", "Geberiyom" }));
        jPanel_halsizlik.add(jComboBox8);
        jComboBox8.setBounds(10, 30, 180, 20);

        jPanel_veriEkle.add(jPanel_halsizlik);
        jPanel_halsizlik.setBounds(220, 30, 200, 100);

        jPanel_hasta.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 204, 255), 7, true));
        jPanel_hasta.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Hasta mısın ?");
        jPanel_hasta.add(jLabel11);
        jLabel11.setBounds(10, 10, 190, 15);

        jComboBox9.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hayir, Degilim", "Evet, Hastayim" }));
        jComboBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox9ActionPerformed(evt);
            }
        });
        jPanel_hasta.add(jComboBox9);
        jComboBox9.setBounds(10, 30, 180, 19);

        jPanel_veriEkle.add(jPanel_hasta);
        jPanel_hasta.setBounds(220, 30, 200, 100);

        AnaPanel.add(jPanel_veriEkle);
        jPanel_veriEkle.setBounds(30, 130, 630, 170);

        label_veriKaydet.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_veriKaydet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Add To Favorite.png"))); // NOI18N
        label_veriKaydet.setText("Veri Girişi");
        label_veriKaydet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_veriKaydet.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        label_veriKaydet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_veriKaydetMouseClicked(evt);
            }
        });
        AnaPanel.add(label_veriKaydet);
        label_veriKaydet.setBounds(240, 40, 140, 50);

        jPanel_benKimim.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 204, 255), 4, true));
        jPanel_benKimim.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Mehmet KARAKAYA");
        jPanel_benKimim.add(jLabel4);
        jLabel4.setBounds(10, 7, 122, 15);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("1421012126");
        jPanel_benKimim.add(jLabel5);
        jLabel5.setBounds(30, 17, 80, 20);

        AnaPanel.add(jPanel_benKimim);
        jPanel_benKimim.setBounds(550, 340, 140, 40);

        labelBackgraund.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/arkaplan.png"))); // NOI18N
        labelBackgraund.setPreferredSize(getMaximumSize());
        labelBackgraund.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        AnaPanel.add(labelBackgraund);
        labelBackgraund.setBounds(0, 0, 690, 380);

        getContentPane().add(AnaPanel);
        AnaPanel.setBounds(0, 0, 690, 380);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void click(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_click
        jPanel_veriEkle.setVisible(false);
        jPanel_veriler.setVisible(true);
        jPanel_sorgulamaYap.setVisible(false);
        veriCek();
    }//GEN-LAST:event_click
    int tik=1;
    double Hhasta;
    private void jLabel_sorgulamaYapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_sorgulamaYapMouseClicked
        jPanel_veriler.setVisible(false);
        jPanel_veriEkle.setVisible(false);
        jPanel_sorgulamaYap.setVisible(true);
        jPanel_sonuc.setVisible(false);
        jPanel_secimYap.setVisible(true);
        try {
            liste = vt.verileriCek();
            //JOptionPane.showMessageDialog(null, "veriler çekildi");
        } catch (SQLException ex) {
            Logger.getLogger(anasayfa.class.getName()).log(Level.SEVERE, null, ex);
        }
        ıd3();
    }//GEN-LAST:event_jLabel_sorgulamaYapMouseClicked

    private void label_kaydetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_kaydetMouseClicked
        tik++;
        if(tik==1){
            jPanel_ates.setVisible(true);
            jPanel_agri.setVisible(false);
            jPanel_halsizlik.setVisible(false);
            jPanel_hasta.setVisible(false);
            jPanel_oksuruk.setVisible(false);
        }
        else if(tik==2){
            jPanel_ates.setVisible(false);
            jPanel_agri.setVisible(false);
            jPanel_halsizlik.setVisible(false);
            jPanel_hasta.setVisible(false);
            jPanel_oksuruk.setVisible(true);
        }
        else if(tik==3){
            jPanel_ates.setVisible(false);
            jPanel_agri.setVisible(true);
            jPanel_halsizlik.setVisible(false);
            jPanel_hasta.setVisible(false);
            jPanel_oksuruk.setVisible(false);
        }
        else if(tik==4){
            jPanel_ates.setVisible(false);
            jPanel_agri.setVisible(false);
            jPanel_halsizlik.setVisible(true);
            jPanel_hasta.setVisible(false);
            jPanel_oksuruk.setVisible(false);
        }
        else if(tik==5){
            jPanel_ates.setVisible(false);
            jPanel_agri.setVisible(false);
            jPanel_halsizlik.setVisible(false);
            jPanel_hasta.setVisible(true);
            jPanel_oksuruk.setVisible(false);
            label_kaydet.setText("Kaydet");
        }
        else if(tik==6){
            label_kaydet.setText("İleri");
            tik=1;
            jPanel_ates.setVisible(true);
            jPanel_agri.setVisible(false);
            jPanel_halsizlik.setVisible(false);
            jPanel_hasta.setVisible(false);
            jPanel_oksuruk.setVisible(false);
            kaydet();
        }
    }//GEN-LAST:event_label_kaydetMouseClicked

    private void veriCek(){
        ArrayList<veriTabani> liste = new ArrayList<veriTabani>();
        veriTabani vt = new veriTabani();
        
        try {
             liste = vt.verileriCek();
        } catch (SQLException ex) {
            Logger.getLogger(anasayfa.class.getName()).log(Level.SEVERE, null, ex);
        }
            String dizi[][]=new String[liste.size()][];
                for (int i = 0; i < liste.size(); i++) {     
                     dizi[i]=new String[]{                                   
                     valueOf(liste.get(i).getAtes()),
                     valueOf(liste.get(i).getOksuruk()),
                     valueOf(liste.get(i).getAgri()),
                     valueOf(liste.get(i).getHalsizlik()),
                     valueOf(liste.get(i).getHasta())
                     };
                     TableModel tabloModeli=new DefaultTableModel(
             dizi,
             new String[] {"ATES", "OKSURUK", "AGRI","HALSİZLİK", "HASTA"}                                                 
                           );
             veriler.setModel(tabloModeli);
                }
    }
    private void kaydet(){
        
        String ates = jComboBox2.getSelectedItem().toString();
        String oksuruk = jComboBox7.getSelectedItem().toString();
        String agri = jComboBox10.getSelectedItem().toString();
        String halsizlik = jComboBox8.getSelectedItem().toString();
        String hasta = jComboBox9.getSelectedItem().toString();
        veriTabani vt = new veriTabani();
        
        try {
            vt.veriEkle(ates,oksuruk,agri,halsizlik,hasta);
        } catch (SQLException ex) {
            Logger.getLogger(anasayfa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox9ActionPerformed

    private void jComboBox10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox10ActionPerformed
        String deg1[][]=new String[3][2];
        String deg2[][]=new String[2][2];
        String deg3[][]=new String[3][2];
        String deg4[][]=new String[2][2];
        String deg5[][]=new String[2][2];
        
        String deg1kazanc[][]=new String[3][2];
        String deg2kazanc[][]=new String[2][2];
        String deg3kazanc[][]=new String[3][2];
        String deg4kazanc[][]=new String[2][2];
        String deg5kazanc[][]=new String[2][2];
        
        String kazanc[][]=new String[4][2];
        
        String secim="";
        String neyegore="";
        ArrayList<veriTabani> liste = new ArrayList<veriTabani>();
        veriTabani vt = new veriTabani();
        
        DecimalFormat df = new DecimalFormat("#.######");
        String araDeger;
    public void ıd3(){
            deg5[0][0]="Hayir, Degilim";        deg5[1][0]="Evet, Hastayim";
            deg5[0][1]="0";                     deg5[1][1]="0";

            deg4[0][0]="iyiyim";        deg4[1][0]="Geberiyom";
            deg4[0][1]="0";            deg4[1][1]="0";

            deg3[0][0]="Eh iste";      deg3[1][0]="Agri dagin eteginde....";    deg3[2][0]="Turp gibiyim";
            deg3[0][1]="0";            deg3[1][1]="0";                      deg3[2][1]="0";

            deg2[0][0]="Hayir";        deg2[1][0]="Evet";
            deg2[0][1]="0";            deg2[1][1]="0";

            deg1[0][0]="33 - 35    Dusuk";        deg1[1][0]="35 - 37    Normal";       deg1[2][0]="37 - 40    Yuksek";
            deg1[0][1]="0";                      deg1[1][1]="0";                     deg1[2][1]="0";
            System.out.println("Seçiminiz  =   "+secim);
            
            
            for (int i = 0; i < liste.size(); i++) {
              
                
                for (int j = 0; j < deg5.length; j++) {
                    if(deg5[j][0].equals(liste.get(i).getHasta())){
                        deg5[j][1]=String.valueOf(Integer.parseInt(deg5[j][1])+1);
                    }
                }



                for (int j = 0; j < deg4.length; j++) {
                    if(deg4[j][0].equals(liste.get(i).getHalsizlik())){
                        deg4[j][1]=String.valueOf(Integer.parseInt(deg4[j][1])+1);
                    }
                }


                for (int j = 0; j < deg3.length; j++) {
                    if(deg3[j][0].equals(liste.get(i).getAgri())){
                        deg3[j][1]=String.valueOf(Integer.parseInt(deg3[j][1])+1);
                    }

                }

                for (int j = 0; j < deg2.length; j++) {
                    if(deg2[j][0].equals(liste.get(i).getOksuruk())){
                        deg2[j][1]=String.valueOf(Integer.parseInt(deg2[j][1])+1);
                    }

                }


                for (int j = 0; j < deg1.length; j++) {
                    if(deg1[j][0].equals(liste.get(i).getAtes())){
                        deg1[j][1]=String.valueOf(Integer.parseInt(deg1[j][1])+1);
                    }

                }
            }
            //System.out.println("deg5 0 tolmam                    ------"+deg5[0][1]);
            //System.out.println("deg5 1 tolmam                    ------"+deg5[1][1]);
            //******************************************Diggat ************************************
            int deger1=(Integer.parseInt(deg5[0][1]));
            int deger2=(Integer.parseInt(deg5[1][1]));
            if(deger2==0){
                System.out.println("\n\n\n\n\n\n");
                System.out.print("Sonuç   =   ");
                System.out.println(deg5[0][0]);
                jPanel_sonuc.setVisible(true);
                jPanel_secimYap.setVisible(false);
                jLabel_sonuc.setText("Yapılan tetkikler sonucunda, SAĞLIKLI olduğunuz tesbit edilmiştir.");
            }
            else if(deger1==0){
                System.out.println("\n\n\n\n\n\n");
                System.out.print("Sonuç   =   ");
                System.out.println(deg5[1][0]);
                jPanel_sonuc.setVisible(true);
                jPanel_secimYap.setVisible(false);
                jLabel_sonuc.setText("Yapılan tetkikler sonucunda, maalesef HASTA olduğunuz tesbit edilmiştir.");
            }
            else{
            double toplam =deger1+deger2;
            Hhasta=(-1)*(((deger1/toplam)*(Math.log(deger1/toplam)/Math.log(2)))  +  ((deger2/toplam)*(Math.log(deger2/toplam)/Math.log(2))));
            araDeger =df.format(Hhasta).replace(',', '.');
            Hhasta=Double.parseDouble(araDeger);
            String[] kazanclar = new String[4];
            //kazancHesap(deg3);
            //yapılacaklar
            //        ondan hiç yoksa combobokxa çektirme....
            kazanclar[0]=String.valueOf(kazancHesap(deg1));
            kazanclar[1]=String.valueOf(kazancHesap(deg2));
            kazanclar[2]=String.valueOf(kazancHesap(deg3));
            kazanclar[3]=String.valueOf(kazancHesap(deg4));

            System.out.println("********** KAZANÇLAR **********");
            System.out.println(kazanclar[0]);
            System.out.println(kazanclar[1]);
            System.out.println(kazanclar[2]);
            System.out.println(kazanclar[3]);
            
            int index=0;
            for (int i = 1; i < kazanclar.length; i++) {
                if(     Double.parseDouble(kazanclar[index])<Double.parseDouble(kazanclar[i])     ){
                    index=i;
                }
            }
            System.out.println("********** YENİ SORGU **********");
            if(index==0){
                neyegore="ates";
                jComboBox_secim.removeAllItems();
                System.out.println("Lütfen Ateş Seviyesi İçin Seçim Yapınız...");
                if(!deg1[0][1].equals("0")){
                    jComboBox_secim.addItem("33 - 35    Dusuk");
                    System.out.println("33 - 35    Dusuk");
                }
                if(!deg1[1][1].equals("0")){
                    jComboBox_secim.addItem("35 - 37    Normal");
                    System.out.println("35 - 37    Normal");
                }
                if(!deg1[2][1].equals("0")){
                    jComboBox_secim.addItem("37 - 40    Yuksek");
                    System.out.println("37 - 40    Yuksek");
                }
            }
            else if(index==1){
                neyegore="oksuruk";
                jComboBox_secim.removeAllItems();
                System.out.println("Lütfen Öksürük Durumu İçin Seçim Yapınız...");
                if(!deg2[0][1].equals("0")){
                    jComboBox_secim.addItem("Hayir");
                    System.out.println("Hayir");
                }
                if(!deg2[1][1].equals("0")){
                    jComboBox_secim.addItem("Evet");
                    System.out.println("Evet");
                }
            }
            else if(index==2){
                neyegore="agri";
                jComboBox_secim.removeAllItems();
                System.out.println("Lütfen Ağrı Seviyesi İçin Seçim Yapınız...");
                if(!deg3[0][1].equals("0")){
                    jComboBox_secim.addItem("Eh iste");
                    System.out.println("Eh iste");
                }
                if(!deg3[1][1].equals("0")){
                    System.out.println("Agri dagin eteginde....");
                    jComboBox_secim.addItem("Agri dagin eteginde....");
                }
                if(!deg3[2][1].equals("0")){
                    jComboBox_secim.addItem("Turp gibiyim");
                    System.out.println("Turp gibiyim");
                } 
            }
            else if(index==3){
                neyegore="halsizlik";
                jComboBox_secim.removeAllItems();
                System.out.println("Lütfen Halsizlik Durumu İçin Seçim Yapınız...");
                if(!deg4[0][1].equals("0")){
                    jComboBox_secim.addItem("iyiyim");
                    System.out.println("iyiyim");
                }
                if(!deg4[1][1].equals("0")){
                    jComboBox_secim.addItem("Geberiyom");
                    System.out.println("Geberiyom");
                }
                
            }
            }
            jLabel_secim.setText(neyegore.toUpperCase()+" Şikayetiniz var mı ?");
            
            
    }    
    private void label_veriKaydetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_veriKaydetMouseClicked
        jPanel_veriEkle.setVisible(true);
        jPanel_veriler.setVisible(false);
        jPanel_sorgulamaYap.setVisible(false);
    }//GEN-LAST:event_label_veriKaydetMouseClicked

    private void jComboBox_secimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_secimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_secimActionPerformed

    private void jLabel_sorgulaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_sorgulaMouseClicked
        secim=jComboBox_secim.getSelectedItem().toString();
        
       // JOptionPane.showMessageDialog(null, secim);
        if(!secim.equals("start")){
            for (int t = 0; t < liste.size(); t++) {
                if(liste.get(t).getAtes().equals(secim)||liste.get(t).getOksuruk().equals(secim)||liste.get(t).getAgri().equals(secim)||liste.get(t).getHalsizlik().equals(secim)){
                }
                else{
                    liste.remove(t);
                    t--;
                }
            }
        }
        ıd3();
    }//GEN-LAST:event_jLabel_sorgulaMouseClicked
    public double kazancHesap(String[][] dizi){
        double hdegisken = 0;
        double kazanc=0;        
        double evetSayisi=0;
        double hayirSayisi=0;
        double toplam=0;
        for (int i = 0; i < dizi.length; i++) {
            toplam = toplam + (Double.parseDouble(dizi[i][1]));
        }
        for (int j = 0; j < dizi.length; j++) {
            for (int i = 0; i < liste.size(); i++) {
                if(liste.get(i).getAtes().equals(dizi[j][0])||liste.get(i).getAgri().equals(dizi[j][0])||liste.get(i).getOksuruk().equals(dizi[j][0])||liste.get(i).getHalsizlik().equals(dizi[j][0]))
                {
                    if(liste.get(i).getHasta().equals("Evet, Hastayim")){
                        evetSayisi++;
                        continue;    
                    }
                    hayirSayisi++;
                }
                
            } 
            hdegisken=0;
            
            if(evetSayisi==0||hayirSayisi==0){
                hdegisken=0;
                //System.out.println("hdegisken 0 için= "+hdegisken);
            }
            else{
                hdegisken = (-1)*(     ((evetSayisi/(evetSayisi+hayirSayisi))*(Math.log((evetSayisi/(evetSayisi+hayirSayisi)))/Math.log(2)))   +   ((hayirSayisi/(evetSayisi+hayirSayisi))*(Math.log((hayirSayisi/(evetSayisi+hayirSayisi)))/Math.log(2)))     );
                araDeger =df.format(hdegisken).replace(',', '.');
                hdegisken=Double.parseDouble(araDeger);
                //System.out.println("hdegisken hesap için= "+hdegisken);
            }
            if(Double.parseDouble(dizi[j][1])==0){
                kazanc=kazanc+0;
                //System.out.println( "kazanç 0 için = "+kazanc);
            }
            else{
                kazanc =kazanc+(       (     (Double.parseDouble(dizi[j][1]))/toplam     )*hdegisken           );
                araDeger =df.format(kazanc).replace(',', '.');
                kazanc=Double.parseDouble(araDeger);
                //System.out.println("kazanç hesap için = "+kazanc);
            }
            System.out.println("Evet Sayısı   =   "+evetSayisi);
            System.out.println("Hayır Sayısı   =   "+hayirSayisi);
            System.out.println("hdegisken   =   "+hdegisken);
            evetSayisi=0;
            hayirSayisi=0;
        }
        
        kazanc=Hhasta-kazanc;
        araDeger =df.format(kazanc).replace(',', '.');
        kazanc=Double.parseDouble(araDeger);
        System.out.println("hHasta :  "+Hhasta);
        System.out.print("Kazanç :   ");System.out.println(kazanc);
        System.out.println("------------------------------------------------");
        return kazanc;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(anasayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(anasayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(anasayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(anasayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new anasayfa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AnaPanel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> jComboBox10;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JComboBox<String> jComboBox9;
    private javax.swing.JComboBox<String> jComboBox_secim;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_secim;
    private javax.swing.JLabel jLabel_sonuc;
    private javax.swing.JLabel jLabel_sorgula;
    private javax.swing.JLabel jLabel_sorgulamaYap;
    private javax.swing.JPanel jPanel_agri;
    private javax.swing.JPanel jPanel_ates;
    private javax.swing.JPanel jPanel_benKimim;
    private javax.swing.JPanel jPanel_halsizlik;
    private javax.swing.JPanel jPanel_hasta;
    private javax.swing.JPanel jPanel_oksuruk;
    private javax.swing.JPanel jPanel_secimYap;
    private javax.swing.JPanel jPanel_sonuc;
    private javax.swing.JPanel jPanel_sorgulamaYap;
    private javax.swing.JPanel jPanel_veriEkle;
    private javax.swing.JPanel jPanel_veriler;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelBackgraund;
    private javax.swing.JLabel labelListele;
    private javax.swing.JLabel label_kaydet;
    private javax.swing.JLabel label_veriKaydet;
    private javax.swing.JTable veriler;
    // End of variables declaration//GEN-END:variables

    
}
